plugins { id 'com.android.application' }
android {
 namespace 'lab.reconcat'
 compileSdk 33
 defaultConfig {
  applicationId 'lab.reconcat'
  minSdk 21
  targetSdk 33
  versionCode 1
  versionName '1.0.0'
 }
 compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
